services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    restart: unless-stopped
    ports:
      - "8088:80"
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    restart: unless-stopped
    env_file:
      - .env.pi
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: -XX:MaxRAMPercentage=75.0
    expose:
      - "8080"
